<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php if ($this->getChild('content')->getArchive()): ?>
        <title><?php echo $this->getChild('content')->getArchive()->getSubject(); ?></title>
    <?php else: ?>
        <title><?php echo $this->__('Email Preview'); ?></title>
    <?php endif; ?>
</head>
<body>
    <?php echo $this->getChildHtml('content') ?>
</body>
</html>
