<?php
/**
 * Created for  Andreani.
 * @author:     mhidalgo@summasolutions.net
 * Date:        01/10/14
 * Time:        09:43
 * @copyright   Copyright (c) 2015 Summa Solutions (http://www.summasolutions.net)
 */
?>
<?php $this->setPriceDataObject($this->getSource()) ?>
<?php if ((float) $this->getSource()->getSummaAndreaniInsuranceAmount()): ?>
    <tr>
        <td class="label"><?php echo Mage::helper('summa_andreani')->getConfigData('insurance_subtotal_title')?></td>
        <td>
            <?php echo $this->displayPrices($this->getSource()->getBaseSummaAndreaniInsuranceAmount(), $this->getSource()->getSummaAndreaniInsuranceAmount()); ?>
        </td>
    </tr>
<?php endif; ?>

