<?php
/**
 * Summa Cms Export Reference template.
 *
 * @category Summa
 * @package  Summa_Cms
 * @author   "Pablo Cianci" <pcianci@summasolutions.net>
 *
 */

/**
 * @var $this Summa_Cms_Block_Adminhtml_Cms_Block_Export|Summa_Cms_Block_Adminhtml_Cms_Page_Export ?>
 */

/**
 * @var $cmsHelper Summa_Cms_Helper_Data
 */
$cmsHelper = $this->helper('summa_cms');
?>
<div class="export-references">
    <div class="title"><?php echo $cmsHelper->__('References'); ?></div>
    <div class="dependency satisfied">
        <span class="icon">&nbsp;</span>
        <span class="explanation">
            <?php echo $cmsHelper->__('Satisfied dependencies that will be included in the export file.'); ?>
        </span>
    </div>
    <div class="dependency non-satisfied">
        <span class="icon">&nbsp;</span>
        <span class="explanation">
            <?php echo $cmsHelper->__('Non satisfied dependencies. You can check the "Auto resolve dependencies" to include them in the export file.'); ?>
        </span>
    </div>
</div>